### ISSUE TITLE
Router should support internal events

### ISSUE THREAD

**Issue by KeithWoods** [esp/esp-net#28]
Affects branch `issues/24`, likely `master` too

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException occurred
  HResult=-2146233088
  Message='object' does not contain a definition for 'PreviewSubject'
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at CallSite.Target(Closure , CallSite , Object )
       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       at Esp.Net.Router.ModelEntry`1.<>c__DisplayClass1d`1.<ProcessEvent>b__1c() in c:\dev\esp\esp-net\Esp.Net\Router.ModelEntry.cs:line 242
  InnerException: 

```

The way events get dispatched (which uses dynamic types) doesn't work well with event declared with an internal scoping

**Comment by KeithWoods** [comment]
On second thoughts this isn't too bad. The router uses the DLR to dispatch events, the DLR can't access internal types. If it was using reflection it could but that's not the current implementation. 

#26 added a fix to catch this RuntimeBinderException and rethrow warning that internal events are not supported without using an InternalsVisibleTo attribute.
